import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx,mdx}",
    "./.storybook/**/*.{ts,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1200px",
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        heading: ["Source Serif 4", "Georgia", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brand: {
          primary: {
            DEFAULT: "hsl(var(--brand-primary))",
            foreground: "hsl(var(--brand-primary-foreground))",
            50: "hsl(var(--brand-primary-50))",
            100: "hsl(var(--brand-primary-100))",
            200: "hsl(var(--brand-primary-200))",
            300: "hsl(var(--brand-primary-300))",
            400: "hsl(var(--brand-primary-400))",
            500: "hsl(var(--brand-primary-500))",
            600: "hsl(var(--brand-primary-600))",
            700: "hsl(var(--brand-primary-700))",
            800: "hsl(var(--brand-primary-800))",
            900: "hsl(var(--brand-primary-900))",
          },
          secondary: {
            DEFAULT: "hsl(var(--brand-secondary))",
            foreground: "hsl(var(--brand-secondary-foreground))",
            50: "hsl(var(--brand-secondary-50))",
            100: "hsl(var(--brand-secondary-100))",
            200: "hsl(var(--brand-secondary-200))",
            300: "hsl(var(--brand-secondary-300))",
            400: "hsl(var(--brand-secondary-400))",
            500: "hsl(var(--brand-secondary-500))",
            600: "hsl(var(--brand-secondary-600))",
            700: "hsl(var(--brand-secondary-700))",
            800: "hsl(var(--brand-secondary-800))",
            900: "hsl(var(--brand-secondary-900))",
          },
          feminine: {
            DEFAULT: "hsl(var(--brand-feminine))",
            foreground: "hsl(var(--brand-feminine-foreground))",
            100: "hsl(var(--brand-feminine-100))",
            200: "hsl(var(--brand-feminine-200))",
            300: "hsl(var(--brand-feminine-300))",
            400: "hsl(var(--brand-feminine-400))",
            500: "hsl(var(--brand-feminine-500))",
            600: "hsl(var(--brand-feminine-600))",
            700: "hsl(var(--brand-feminine-700))",
          },
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--brand-primary-50))",
          100: "hsl(var(--brand-primary-100))",
          200: "hsl(var(--brand-primary-200))",
          300: "hsl(var(--brand-primary-300))",
          400: "hsl(var(--brand-primary-400))",
          500: "hsl(var(--brand-primary-500))",
          600: "hsl(var(--brand-primary-600))",
          700: "hsl(var(--brand-primary-700))",
          800: "hsl(var(--brand-primary-800))",
          900: "hsl(var(--brand-primary-900))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "hsl(var(--brand-secondary-50))",
          100: "hsl(var(--brand-secondary-100))",
          200: "hsl(var(--brand-secondary-200))",
          300: "hsl(var(--brand-secondary-300))",
          400: "hsl(var(--brand-secondary-400))",
          500: "hsl(var(--brand-secondary-500))",
          600: "hsl(var(--brand-secondary-600))",
          700: "hsl(var(--brand-secondary-700))",
          800: "hsl(var(--brand-secondary-800))",
          900: "hsl(var(--brand-secondary-900))",
        },
        feminine: {
          DEFAULT: "hsl(var(--brand-feminine))",
          foreground: "hsl(var(--brand-feminine-foreground))",
          100: "hsl(var(--brand-feminine-100))",
          200: "hsl(var(--brand-feminine-200))",
          300: "hsl(var(--brand-feminine-300))",
          400: "hsl(var(--brand-feminine-400))",
          500: "hsl(var(--brand-feminine-500))",
          600: "hsl(var(--brand-feminine-600))",
          700: "hsl(var(--brand-feminine-700))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "whatsapp-ping": {
          "0%": { transform: "scale(1)", opacity: "0.75" },
          "75%, 100%": { transform: "scale(1.6)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "whatsapp-pulse": "whatsapp-ping 2s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
